### ISSUE TITLE
Could I please get some help figuring out these errors?

### ISSUE THREAD

**Issue by BlakeBrown** [Emurgo/cardano-serialization-lib#241]
I have a working transaction in cardano-cli, but I'm having trouble constructing the same one using the serialization-lib. Does anyone know what these errors mean?? I tried looking into the typescript definitions, but the documentation isn't great.

```
""transaction submit error ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [
UtxowFailure (NonOutputSupplimentaryDatums (fromList [SafeHash \"9cbcced629edb13ecef78c9c27adfe079a9acd77b62a6693eab0134920a595b9\"]) (fromList [])),
UtxowFailure (ExtraRedeemers [RdmrPtr Spend 1]),
UtxowFailure (WrappedShelleyEraFailure (MissingScriptWitnessesUTXOW (fromList [ScriptHash \"25da22dfd99bf874e59d74c304a1d28e921310327c3e4d6960123f2e\"]))),
UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (UtxosFailure (CollectErrors [NoWitness (ScriptHash \"25da22dfd99bf874e59d74c304a1d28e921310327c3e4d6960123f2e\")]))))])""
```

**Comment by vsubhuman** [comment]
@BlakeBrown , the errors you have provided are from the [cardano-node](https://github.com/input-output-hk/cardano-node), not from the serialisation-lib, so cannot give you a 100% diagnosis but it seems like you have an invalid datum there an invalid redeemer and a missing witness for the script `25da22dfd99bf874e59d74c304a1d28e921310327c3e4d6960123f2e`.

Can you rather provide the code how you build the construction using the serialization-lib and the explanation on what you are trying to achieve? This way we can try help check if you are setting all the things correctly

**Comment by BlakeBrown** [comment]
Thanks for @vsubhuman! I created a [gist](https://gist.github.com/BlakeBrown/b11768e6d09676d39445702a92ed7b81) here which should have all the relevant details, please let me know if you believe I'm missing anything.

The datum hash matches that of the UTXO I'm trying to consume at the script address, so I don't think that would be it?

I'm not sure if my redeemer is correct, but the JSON for it is just `{"constructor":1,"fields":[]}` so I'm not sure why my code would mess such a simple redeemer up.

My guess is I'm not hashing the script properly. Do you know what `PlutusScript.new(hex...?)` accepts? Is it the CBOR hex of the compiled script or something else?

**Comment by BlakeBrown** [comment]
Updated: was able to turn `NonOutputSupplimentaryDatums` into a different error `PPViewHashesDontMatch`. Any idea how resolve this one?

**Comment by rooooooooob** [comment]
>PPViewHashesDontMatch

This might be due to an issue which was fixed in #217 which has been merged but hasn't been included in a release yet. It is set to be included in version [10.0.0](https://github.com/Emurgo/cardano-serialization-lib/milestone/5)

I can't be 100% sure that that's what was causing your issue but I think that could likely be it, since a minor discrepency between how cardano-node and the specs/cardano-serialiazation-lib caused differing hashes being computed.

**Comment by BlakeBrown** [comment]
I'm using @alessandrokonrad's custom version of this library that includes the languageViews , so I don't think that's the issue.

I have another question related to this, how are redeemers created using this library? In `cardano-cli`, we just need to pass a link to the redeemer file. However, here it seems we need:

```
static new(tag: RedeemerTag, index: BigNum, data: PlutusData, ex_units: ExUnits): Redeemer;
```

What are these? The one I really don't understand is `ExUnits`, how can I calculate this?

**Comment by AlainMgz** [comment]
Hey, would like to know how did you solved this issue. Thanks

**Comment by vsubhuman** [comment]
> What are these? The one I really don't understand is `ExUnits`, how can I calculate this?

Ah, yeah. Those are execution units. This is like GAS in ethereum where every Plutus operation has a cost of some number of execution units and then each execution unit has a certain price in Lovelaces from protocol parameters. If you provide an insufficient estimation of ExUnits and not enough fee ADA to cover it - the tx will fail the second level validation (script running basically) and it will be included in the chain but considered as failed, and the "collateral inputs" will be burned (don't forget you gotta include collateral inputs to be burned in case your tx fails).

The only way to estimate the ExUnits as far as I know if to use the PAB (Plutus Execution Backend) which provides functionality to both validate your script, if it will fail or not, and to provide the estimation of ex-units

**Comment by ernestocoinweb** [comment]
Maybe you can calculate the `ExUnits` using the `Cardano.Ledger.Alonzo.TxInfo` haskell module provides the function:

`exBudgetToExUnits :: ExBudget -> Maybe ExUnits`

You can import and use it inside in the file [marketplutus.hs](https://github.com/BlakeBrown/Vendere/blob/main/app/market-plutus.hs#L41) like this:

```
do 
   print ("Ex Budget" :: String) >> print exbudget
   print ("Ex Units" :: String)  >> print (exBudgetToExUnits exbudget)

```

**Comment by AngelCastilloB** [comment]
I am having the exact same issues, for context, I am creating and deploying the smart contract from the Cardano CLI, I can then interact with the smart-contract using the CLI with no issues, now, when trying to create a transaction with the serialization lib I get the same error as the OP mentioned in this issue, I compared the CBOR data of the datum and redeemer generated by both the Carcano CLI and the Serialization lib and they do not match:

My contract expects one redeemer and two datums (the original datum already sitting at the eUTXO and the new datum for the new eUTXO).

### First datum:

**CLI JSON format:**

`{"constructor":0,"fields":[{"int":0}]}`

**CLI CBOR output:**

`d8799f00ff80f5f6`

Serialization LIB generation code:
```javascript
    let fieldsInner = EmurgoSerialization.PlutusList.new();
    fieldsInner.add(EmurgoSerialization.PlutusData.new_integer(EmurgoSerialization.BigInt.from_str("0")));
    return EmurgoSerialization.PlutusData.new_constr_plutus_data(
      EmurgoSerialization.ConstrPlutusData.new(
        EmurgoSerialization.Int.new_i32(0),
        fieldsInner
      )
    );
```
**Serialization LIB Output:**

`d866820081c24100`

### Second Datum:

**CLI JSON format:**

`{"constructor":0,"fields":[{"int":1}]}`

**CLI CBOR output:**

`d8799f01ff80f5f6`

Serialization LIB generation code:

```javascript
    let fieldsInner = EmurgoSerialization.PlutusList.new();
    fieldsInner.add(EmurgoSerialization.PlutusData.new_integer(EmurgoSerialization.BigInt.from_str("1")));

    return EmurgoSerialization.PlutusData.new_constr_plutus_data(
      EmurgoSerialization.ConstrPlutusData.new(
        EmurgoSerialization.Int.new_i32(0),
        fieldsInner
      )
    );
```

**Serialization LIB Output:**

`d86682008101`

### Redeemer:

**CLI JSON format:**

`{"constructor":0,"fields":[{"int":0},{"bytes":"71af771c8a6b10931f5ad9acf7597780ae98eb3518a231575a21e926a9b2249b"}]}`

**CLI CBOR output:**

`d8799f00582071af771c8a6b10931f5ad9acf7597780ae98eb3518a231575a21e926a9b2249bff80f5f6`

Serialization LIB generation code:
```javascript
   const fieldsInner = EmurgoSerialization.PlutusList.new();
    fieldsInner.add(EmurgoSerialization.PlutusData.new_integer(EmurgoSerialization.BigInt.from_str("0")));
 fieldsInner.add(EmurgoSerialization.PlutusData.new_bytes(this.fromHex("71af771c8a6b10931f5ad9acf7597780ae98eb3518a231575a21e926a9b2249b")));
    const redeemerData = EmurgoSerialization.PlutusData.new_constr_plutus_data(
      EmurgoSerialization.ConstrPlutusData.new(
        EmurgoSerialization.Int.new_i32(0),
        fieldsInner
      )
    );
```
**Serialization LIB Output:**

`d866820082c24100582071af771c8a6b10931f5ad9acf7597780ae98eb3518a231575a21e926a9b2249b`

So none of the hashes match. I wonder if the solution is to also deploy the contract using the serialization lib so the datum hashes will match, I still don't understand why I get the error "extra redeemer".

Any pointers in the right direction would be appreciated. I am thinking to just replace the datums before signing the transaction, and then again on the signed transaction, but the issue is that one of the datums do not match in length, so I am pretty sure that wont work

**Comment by Mercurial** [comment]
> reserializes

I believe the extra redeemer error is because you need to specify what input index the redeemer will be used with. Other wise it will think you haven't provided a redeemer for your input

**Comment by BlakeBrown** [comment]
I forgot I still had this issue open 😅 

Unfortunately cannot remember the solution to my specific problem. If I recall correctly, it just took a very long time to get setup with the library. Would be awesome if we could add some examples of how to use 10.0.0 when it comes out as I think this would help unblock the majority of the folks here.

**Comment by AngelCastilloB** [comment]
The problem was the Plutus script, I had to remove the initial 3 bytes from it, otherwise, it will give the missing witness, and mark the redeemer as "extra" as there was no script.

Btw if anyone encounters a similar issue (interoperability between contracts deployed with the CLI and Nami wallet/serialization lib), replacing the datums on the serialization lib with the ones generated by the CLI works, you just need to also replace the datum hashes and recalculate the script data hash with the new datum data.

This will allow you to interact with contracts from the Nami wallet that were deployed from the CLI at least until Nami wallet upgrades its serialization lib, then this won't be needed as lib 10.0.8-beta already serializes the datums that are compatible with the CLI.

**Comment by BlakeBrown** [comment]
Great summary @AngelCastilloB
