### ISSUE TITLE
Error: Uncaught (in promise) Script inputs not supported yet

### ISSUE THREAD

**Issue by pyropy** [Emurgo/cardano-serialization-lib#279]
## Problem

When trying to add input UTxO that is sitting on smart contract address I get following error:

```text
Uncaught (in promise) Script inputs not supported yet
```

I use latest beta release. I'm wondering what I'm doing wrong as I know some people have already integrated cardano-serialization-lib with smart contracts.

## Code

Currently we have hard coded adding the inputs just for testing purposes.

```typescript
import { WasmT } from "./types";

export const getScriptUtxo = (wasm: WasmT) => wasm.TransactionInput.new(
  wasm.TransactionHash.from_bytes(Buffer.from('a22618236a2b2e5f780ed0dd36a2b485108dae2c13bf051ed1915eabe6bf0765', "hex")),
  1
);


const buildTx = (wasm: WasmT) => {

  const { txBuilder } = initTx(wasm);
  
  // hard-coded script input
  txBuilder.add_input(
    wasm.Address.from_bech32("addr_test1wpr9gxjzne57z6sfpgkx9gh5x3nmmtpnrdzwnnem4n2u86q80se5k"),
    getScriptUtxo(wasm),
    wasm.Value.new(wasm.BigNum.from_str("4999000"))
  )
}

```

**Comment by vsubhuman** [comment]
Hi, @pyropy! Yes, this code is still there, because the questions of witnesses and fee-stimation has not yet been properly addressed.

You can try using version `10.0.0-beta.8` which actually has this one assertion line disabled, so you will be able to add the input, but note that you gonna need to also add the script into witnesses, which is not supported by the builder yet, so you'd have to use the rsulting tx to do it manually. But this means the automatic fee estimation will be incorrect because it will not know about the witness script. You can work around it by setting the fee value manually to something big, like 2 ADA.

Check version 10 release notes first, there are some breaking changes there, but if you start using that lib you gonna have to update to that version anyways. We are about to release it soon, so not would be the best time.

https://github.com/Emurgo/cardano-serialization-lib/releases/tag/untagged-38227e1d0ee851c64be5

**Comment by pyropy** [comment]
@vsubhuman I've downloaded both source-code and npm package for `10.0.0-beta.8` version and seems like the code is still there.

<img width="789" alt="Screenshot 2021-12-06 at 13 19 29" src="https://user-images.githubusercontent.com/30221068/144844981-b8526c91-8bc3-4bf8-a121-23725f3a81c4.png">

**Comment by vsubhuman** [comment]
> @vsubhuman I've downloaded both source-code and npm package for `10.0.0-beta.8` version and seems like the code is still there.

In the codebase the code is still there, but in the published npm package it's been removed. Try it out plz and see if you will be getting the same error still.

**Comment by pyropy** [comment]
@vsubhuman This is result of cat command on `node_modules/@emurgo/cardano-serialization-lib-browser/package.json`

```json
{
  "name": "@emurgo/cardano-serialization-lib-browser",
  "collaborators": [
    "EMURGO"
  ],
  "description": "(De)serialization functions for the Cardano blockchain along with related utility functions",
  "version": "10.0.0-beta.8",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Emurgo/cardano-serialization-lib.git"
  },
  "files": [
    "cardano_serialization_lib_bg.wasm",
    "cardano_serialization_lib.js",
    "cardano_serialization_lib.d.ts",
    "cardano_serialization_lib.js.flow",
    "cardano_serialization_lib_bg.js"
  ],
  "module": "cardano_serialization_lib.js",
  "types": "cardano_serialization_lib.d.ts",
  "sideEffects": "false",
  "author": "EMURGO"
}
```

.. Yet I still get the same error.

**Comment by AngelCastilloB** [comment]
I also tested this and it's still happening from both using the compiled version from the repo and using the package published on npm:

MD5 of the **cardano_serialization_lib_bg.wasm** compiled from the tag: 

`fc1c7bd3911ba2e4a90d5eff42ea9ee8`

MD5 of the **cardano_serialization_lib_bg.wasm** on the NPM package:

`8b95e7be40e444eb0ee64d8e7fdbbea1`

**Comment by vsubhuman** [comment]
Doesn't happen anymore in the latest version
