### ISSUE TITLE
Add usage documentation

### ISSUE THREAD

**Issue by roccomuso** [Emurgo/cardano-serialization-lib#28]
Can you add some examples and documentation?

**Comment by SebastienGllmt** [comment]
Unfortunately because of the really tight timelines set by IOHK, we just don't have time to document this properly so you'll have to just reference the code we've already written. 

I suggest you look at 
1. Our JS test in this repo [here](https://github.com/Emurgo/cardano-serialization-lib/blob/master/src/index.spec.ts)
2. The Rust tests (in the respective Rust files)
3. Our test inside the Yoroi Extension repository [here](https://github.com/Emurgo/yoroi-frontend/blob/develop/app/api/ada/transactions/shelley/transactions.js)

Integration into the Yoroi Extension is still on-going, but we'll continue to add more functionality over the coming week(s).

**Comment by SebastienGllmt** [comment]
With the initial release done, I think it makes sense to try and get back to this now

**Comment by SebastienGllmt** [comment]
Closing since we added documentation a while back for the core functionality.
