### ISSUE TITLE
Error , TransactionMetadata.new(metadata ) , 

### ISSUE THREAD

**Issue by qichalerm** [Emurgo/cardano-serialization-lib#284]
Help!,
Cannot read properties of undefined (reading 'new')

 const METADATA = {
            [policy.id]: {
                [name.slice(0,32)]: {
                    image: `ipfs://${ipfshash}`
                }
            }
        }

const generalMetadata = Loader.Cardano.GeneralTransactionMetadata.new()
generalMetadata.insert(
    Loader.Cardano.BigNum.from_str("721"),
    Loader.Cardano.encode_json_str_to_metadatum(JSON.stringify(metadata))
)
console.log(generalMetadata)
_metadata = Loader.Cardano.TransactionMetadata.new(generalMetadata)
rawTxBody.set_metadata_hash(Loader.Cardano.hash_metadata(_metadata))

Thank.

**Comment by vsubhuman** [comment]
Hi, @qichalerm , which version are you using?

**Comment by qichalerm** [comment]
@emurgo/cardano-serialization-lib-browser": "^9.1.2"

**Comment by vsubhuman** [comment]
Once you have created GeneralTransactionMetadata , you need to set it into an instance of AuxiliaryData, which is the new type introduced in Cardano Alonzo.

See code example here in functions `set_metadata` and `add_metadatum` - https://github.com/Emurgo/cardano-serialization-lib/blob/master/rust/src/tx_builder.rs#L597-L614

Another point is that we are about to release new version 10 with a buncha breaking changes so it would make sense for you to start upgrading for it right away.

There's version `10.0.0-beta.8` availability in NPM at the moment and you can check the release notes here https://github.com/Emurgo/cardano-serialization-lib/pull/283

**Comment by rooooooooob** [comment]
In case it's relevant to anyone, here's why the change was made:

We renamed `TransactionMetadata` to `AuxiliaryData` since after every hardfork it made less and less sense. Shelley-MA (Alegra/Mary) made it have a native scripts containing variant instead of just the metadata that was in the first iteration of Shelley and also renamed it in the spec to `auxiliary_data` but we kept it as `TransactionMetadata` to preserve backwards compatability. Alonzo added in a bunch of plutus scripts/data/etc so we found it wasn't worth it to keep it named `TransactionMetadata` just in the name of backwards compatibility since it had by then evolved to much, much more.

@qichalerm 

So just replace:
```
_metadata = Loader.Cardano.TransactionMetadata.new(generalMetadata)
rawTxBody.set_metadata_hash(Loader.Cardano.hash_metadata(_metadata))
```
with
```
_metadata = Loader.Cardano.AuxiliaryData.new()
_metadata.set_metadata(generalMetadata)
rawTxBody.set_auxiliary_data_hash(Loader.Cardano.hash_auxiliary_data(_metadata))
```
and you should be fine, although I would also recommend renaming `_metadata`.

**Comment by qichalerm** [comment]
@rooooooooob @vsubhuman 
Thank.
