### ISSUE TITLE
how to write TransactionOutputs hash for this?

### ISSUE THREAD

**Issue by mailtodanish** [Emurgo/cardano-serialization-lib#333]
```
{
        "constructor":0,
        "fields":
        [
                {
                        "int":35
                }
        ]
}
```
I have written following way but it is not working at CLI level. Error: "The Plutus script witness has the wrong datum (according to the UTxO). The expected datum value has hash "08e782b1e33069a20879aff23ca94423333ebe0bcf134f367ff240cbbe637496""

let outputs = this.S.TransactionOutputs.new();
const datums = this.S.PlutusList.new();
const plutusList = this.S.PlutusList.new();
plutusList.add(
this.S.PlutusData.new_integer(this.S.BigInt.from_str("35"))
);

const datum = this.S.PlutusData.new_constr_plutus_data(
this.S.ConstrPlutusData.new(this.S.Int.new_i32(0), plutusList)
);
datums.add(datum);

let t = this.S.TransactionOutput.new(
this.S.Address.from_bech32(ReceiveAddress),
outputValue
);

t.set_data_hash(this.S.hash_plutus_data(datum));

outputs.add(t);

**Comment by mailtodanish** [comment]
I have written following way but it is not working at CLI level. Error: "The Plutus script witness has the wrong datum (according to the UTxO). The expected datum value has hash "08e782b1e33069a20879aff23ca94423333ebe0bcf134f367ff240cbbe637496""
```
let outputs = this.S.TransactionOutputs.new();
const datums = this.S.PlutusList.new();
const plutusList = this.S.PlutusList.new();
plutusList.add(
this.S.PlutusData.new_integer(this.S.BigInt.from_str("35"))
);

const datum = this.S.PlutusData.new_constr_plutus_data(
this.S.ConstrPlutusData.new(this.S.Int.new_i32(0), plutusList)
);
datums.add(datum);


let t = this.S.TransactionOutput.new(
this.S.Address.from_bech32(ReceiveAddress),
outputValue
);

t.set_data_hash(this.S.hash_plutus_data(datum));

outputs.add(t);
```

**Comment by rooooooooob** [comment]
How was this datum originally created to put on-chain? Due to how [CBOR](https://datatracker.ietf.org/doc/html/rfc7049) works you can have two datums that are semantically equivalent but due to stuff like indefinite lengths vs definite or different integer encodings (think of the number 0 as a 16-bit vs 32-bit byte representation) they are serialized differently as bytes, causing a different hash.

For this reason unless you are constructing your own datum in the first place, you should only be constructing it via `PlutusData.from_bytes()` / `PlutusList.from_bytes()`.

However this is not as of 9.1.4 working quite either since the PR #317 that maintains the deserialized byte format exactly upon re-serialization hasn't been merged yet. Hopefully we can get it merged soon.

**Comment by mailtodanish** [comment]
`For this reason unless you are constructing your own datum in the first place, you should only be constructing it via PlutusData.from_bytes() / PlutusList.from_bytes().`

You mean we can use only like below or ? please provide me example.
fields.add(Load.cardano.PlutusData.new_bytes(Buffer.from('3f7826896a48c593598465a096d63606ceb8206', 'hex')));

**Comment by mailtodanish** [comment]
@rooooooooob  please suggest how to make it working

**Comment by rooooooooob** [comment]
@mailtodanish you need to have the entire serialized bytes of the whole datum how it was created by the cli and then you'll need to use `PlutusData.from_bytes()` and stick the whole bytes there. Do NOT use `PlutusData.new_bytes()` as this will create a NEW bytes datum (i.e. `{"bytes": "3f7826896a48c593598465a096d63606ceb8206"}`), rather than deserialize one from bytes. I hope this helps.

Where did you get `3f7826896a48c593598465a096d63606ceb8206` from? I can't seem to decode that as CBOR to see what it is supposed to be datum-wise. It is an odd length string too so I think it's missing a character.

**Comment by mailtodanish** [comment]
@rooooooooob  below is my datum
```
{
        "constructor":0,
        "fields":
        [
                {
                        "int":35
                }
        ]
}
```
I create TransactionOutputs  for above datum but not able to unlock using CLI.

**Comment by rooooooooob** [comment]
As I said earlier, you need to use the same serialized bytes that were used by the cardano-cli to generate the datum hash that created the UTXO. I believe you should be able to find those files as intermediates generated by the cardano-cli maybe as some `cborHex` field somewhere? You'll also need to wait for #317 to get merged unless you're working off of that branch.
