### ISSUE TITLE
Stake key bech32 not working

### ISSUE THREAD

**Issue by MartinSchere** [Emurgo/cardano-serialization-lib#337]
When trying to get an address' stake key, `to_bech32()` returns the wrong result

```js
const getAddressStakeKey = async (addr) => {

  const base = BaseAddress.from_address(Address.from_bech32(addr));
  const stake = base.stake_cred().to_keyhash().to_bech32("stake"); // Not the correct stake key
  const stakeHex = toHex(base.stake_cred().to_keyhash().to_bytes()); // Correct!

  return stake;
};
```

**Comment by rooooooooob** [comment]
@MartinSchere Perhaps there's some confusion here between formats? I just tested it and `ScriptHash::to_bech32()` is giving me the same bytes when I deserialize that string back into a `ScriptHash` as the hex would go.

Bech32 has a prefix and also checksum (to detect people incorrectly entering these in by hand) as well as the raw data payload in base32. Hex(base16) is just the raw bytes encoded as a base16 string.

Bech32 is usually used for addresses but we provide it for some other types as well like keys/hashes.

We can add in a `to_hex()`/`from hex()` function for hashes if that's what you're looking for (also see #293). Otherwise you'll have to use your own hex conversion + `to_bytes()`/`from_bytes()`.

**Comment by MartinSchere** [comment]
Sorry for the vague explanation.

I meant that the base16 encoding is indeed the correct stake key hash (in its base16 format), while the bech32 one is incorrect (in bech32).

If I go to cardanoscan or blockfrost and look up this stake address, the base16 format matches, while the other one doesn't. 

My theory is that there is an older version of bech32 used in the serialization lib.

**Comment by MartinSchere** [comment]
![Frame 1238](https://user-images.githubusercontent.com/61954243/150683816-f3991cb5-d2a9-4746-9ac0-4782b5d3293a.png)

**Comment by rooooooooob** [comment]
@MartinSchere I tried updating the bech32 dependency in our lib and they have changed their API slightly. There is indeed a new version which supports 2 variants of bech32: BIP-0173 (what we use) and BIP-0350 (support added when I upgraded `bech32` from `0.7.2` to the latest `0.8.1`).

I took your hash (I hope I typed this right since it was an image)
`4c8db69f4bfb945dd8d4691f0c73ebce549da5faf05cb213ff7cddee`

and with BIP-0173 I get:
`stake1fjxmd86tlw29mkx5dy0scultee2fmf067pwtyyll0nw7u5q3h57`

and with BIP-0350 I get:
`stake1fjxmd86tlw29mkx5dy0scultee2fmf067pwtyyll0nw7upupm3u`

neither of which seem to be what it says there and it's just the checksum that BIP-0350 changes. Maybe I typed the hash incorrectly and confused a `d` with a `b` or something but I did double-check it by eye once.

**Comment by MartinSchere** [comment]
@rooooooooob Yes, the hash was:

4c8db69f4bfb945dd8d4691f0c73ebce549da5faf05cb213ff7cddee (hex)
stake1u9xgmd5lf0aeghwc63537rrna089f8d9ltc9evsnla7dmmsjyh23q (bech32)

Version doesn't seem to be the issue then...

**Comment by MartinSchere** [comment]
I am placing a bounty of 500 ADA to the person who solves this.

**Comment by kodemill** [comment]
> @rooooooooob Yes, the hash was:
> 
> 4c8db69f4bfb945dd8d4691f0c73ebce549da5faf05cb213ff7cddee (hex) stake1u9xgmd5lf0aeghwc63537rrna089f8d9ltc9evsnla7dmmsjyh23q (bech32)
> 
> Version doesn't seem to be the issue then...

Hello, the `BECH32` string you see in CardanoScan (and other places), is the bech32 encoded reward address: `bech32(networkId + keyHash)`. (The correct bech32 prefix for the *stakeKeyHash* would be `stake_vkh` according to this [CIP](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0005#hashes).)

With your example, this is how you could get the correct bech32 reward address:
```javascript
const getAddressStakeKey = async (addr) => {
  const address = Address.from_bech32(addr);
  const base = BaseAddress.from_address(address);
  const stake = RewardAddress.new(address.network_id(), base.stake_cred())
      .to_address().to_bech32();
  return stake;
};
```

**Comment by MartinSchere** [comment]
@kodemill Well now I feel dumb haha, those were the easiest 500 ADA made. 

Thanks a lot! dm me your address @scheredev on twitter

**Comment by kodemill** [comment]
> @kodemill Well now I feel dumb haha, those were the easiest 500 ADA made.
> 
> Thanks a lot! dm me your address @scheredev on twitter

I'm glad I could help! Please donate the reward to the developers of this awesome library, if it's possible :)
