### ISSUE TITLE
how to know txid#outputid?

### ISSUE THREAD

**Issue by mailtodanish** [Emurgo/cardano-serialization-lib#339]
We need to know **output id** of tx ,It should be like txid#outputid, Usually it's 0 or 1..

**Comment by rooooooooob** [comment]
If I'm understanding your question correctly, the output id is in reference to one of the outputs in a transaction. So if you had a transaction with txid `76ad686e76ad76b6876c876d768` with 3 outputs then to reference the first output you'd have `76ad686e76ad76b6876c876d768#0` and the second output `76ad686e76ad76b6876c876d768#1`, etc.

I'm closing this issue since this is more of a utxo-model/cardano question and not specific to cardano-serialization-lib. If your issue was something specific to this library relating to output indices please just comment again in this issue.

If you were looking for a getter on `TransactionOutput` we don't store the index inside of them since they're defined by their order in `TransactionOutputs` and it is easily computed if you have the index which you'd need to get the `TransactionOutput` from the `TransactionOutputs` to begin with.

I hope this helps.
