### ISSUE TITLE
TransactionBuilder Help and DOCs

### ISSUE THREAD

**Issue by bakon11** [Emurgo/cardano-serialization-lib#348]
Hello,

I am currently trying to follow the following example to create a TX and keep running into few small issues.

https://github.com/Emurgo/cardano-serialization-lib/blob/master/doc/getting-started/generating-transactions.md

This is currently my code for now trying to just add a simple input but I just get this error: 

Property 'hash' does not exist on type 'Bip32PublicKey'.
prvKey.to_public().hash(),`

Here is my code below the `prvKey` has been modified not to expose the real xprv.

```// instantiate the tx builder with the Cardano protocol parameters - these may change later on
const txBuilder = CardanoWasm.TransactionBuilder.new(
    // all of these are taken from the mainnet genesis settings
    // linear fee parameters (a*size + b)
    CardanoWasm.LinearFee.new(CardanoWasm.BigNum.from_str('44'),CardanoWasm.BigNum.from_str('155381')), // linear_fee: LinearFee, 
    // minimum_utxo_val: BigNum, 
    CardanoWasm.BigNum.from_str('1000000'), // minimum_utxo_val: BigNum, 
    // pool_deposit: BigNum, 
    CardanoWasm.BigNum.from_str('500000000'), // pool_deposit: BigNum, 
    // key_deposit: BigNum, 
    CardanoWasm.BigNum.from_str('2000000'), // key_deposit: BigNum, 
    // max_value_size: number, 
    5000,  // max_value_size: number, 
    // max_tx_size: number
    16384  // max_tx_size: number
);

// add a keyhash input - for ADA held in a Shelley-era normal address (Base, Enterprise, Pointer)
const key = "xprv13zlhr447un07...............tda502ymwf"
const prvKey = CardanoWasm.Bip32PrivateKey.from_bech32(key);


txBuilder.add_key_input(
    prvKey.to_public().hash(),
    CardanoWasm.TransactionInput.new(
        CardanoWasm.TransactionHash.from_bytes(
            Buffer.from("2ba8378410e48401bc63409686cafb55372c169e9fdffb47839d3acf27d589e1", "hex")
        ), // tx hash
        0, // index
    ),
    CardanoWasm.Value.new(CardanoWasm.BigNum.from_str('9990000000'))
);

**Comment by rooooooooob** [comment]
@bakon11 Try `prvKey.to_public().to_raw_key().hash()`. We only have hash/sign/etc on the regular EdDSA25519 keys, not the ones with bip32 chain-code information (extra data for the derivation tree). In the example you linked we're constructing the `PrivateKey` directly instead of deriving from a root key.

**Comment by bakon11** [comment]
Fantastic that worked. Really appreciate the tip, just needed to `prvKey.to_raw_key()` in the keyhash witnesses as well.

So does the example in the link above create a full signed TX to be able to send it off with lets say cardano-cli?

This is what I get after I: `console.log(Buffer.from(transaction.to_bytes()).toString("hex"));`

`84a400818258202ba8378410e48401bc63409686cafb55372c169e9fdffb47839d3acf27d589e100018282583900fb913b5fc4970dd2ec10b028c7562cc887821db5a44c24e6cb1f7875a8422ec53939ef5e4d7779d29f7f6996ade63f2cad2289808ee41a9b1a0098968082583900fb913b5fc4970dd2ec10b028c7562cc887821db5a44c24e6cb1f7875a8422ec53939ef5e4d7779d29f7f6996ade63f2cad2289808ee41a9b1b0000000252d824d3021a0002922d031a000641a5a10081825820cb6a2885ddad4f597185efe81758f0869c152478622bfb3e20215a0987b8ccd7584059ebe91660a864f852a4b26b49012575520a708420389bf0cd60708f29adcf3bcc6e726fc5a1248f1cd69408d03641e5f9420fd013274c04cf148226658ba408f5f6`

AGAIN THANK YOU.

**Comment by rooooooooob** [comment]
@bakon11 Yeah it should work, although you'd need a valid tx of course so just posting that tx from the example would fail ledger checks since those addresses/keys/etc are probably made up or invalid by now. The TTL might cause it to not work as well so make sure that that's updated as well (I see your CBOR hex contains the same TTL as the example). The TTL is an upper slot bound of when the tx can be included so must be in the future.

I'm going to mark this issue as closed if that's fine with you since your first issue has been resolved (the `to_raw_key()` part).
