### ISSUE TITLE
Wrong collateral field position in serialized transaction body

### ISSUE THREAD

**Issue by APshenkin** [Emurgo/cardano-serialization-lib#408]
cardano-cli puts collateral filed (13) in transaction body after inputs (0). But `cardano-serialization-lib` order all fields in transaction body. So then if you have transaction body and signature from cardano-cli and try to assemble it with `cardano-serialization-lib` you get invalid transaction

I used https://cbor.me/ to check the problem

here is example of transactionBody from cardanoCli
```
A600818258208D70C538E5D289E2820CC34A7ECC062D7F4F73A4C35513CB4B2BAD50C895ED63000D80018282581D71BA158766C1BAE60E2117EE8987621441FAC66A5E0FB9C7ACA58CF20A1A298AFB8582581D71BA158766C1BAE60E2117EE8987621441FAC66A5E0FB9C7ACA58CF20A1A000F422A021A000287B103000E80
```

You can see that (13) field is after 0

but if you load it to library and then export back you will get this data
```
A600818258208D70C538E5D289E2820CC34A7ECC062D7F4F73A4C35513CB4B2BAD50C895ED6300018282581D71BA158766C1BAE60E2117EE8987621441FAC66A5E0FB9C7ACA58CF20A1A298AFB8582581D71BA158766C1BAE60E2117EE8987621441FAC66A5E0FB9C7ACA58CF20A1A000F422A021A000287B103000D800E80
```

I don't know why it's not ordered on cardano-node side and who should I address this issue, but decided to start from library :)

**Comment by ozgrakkurt** [comment]
@vsubhuman Does this mean that a tx created and signed with cli won't work if imported with serialization lib? Is this a problem? 

Also I found a similar issue [here](https://github.com/dhall-lang/dhall-lang/issues/387)

This might be because we are using a hashmap structure to hold these and we might need to use indexmap or something like that so they stay ordered

**Comment by rooooooooob** [comment]
@APshenkin Is this causing an issue somewhere? They should both be equivalent in CBOR, and when creating TX hashes, both should be serialized in canonical form (i.e. using the order we have - see CBOR RFC).

There is no "right" or "wrong" ordering in CBOR key ordering unless specified by some other standard (e.g. canonical form for hashing - but the body on-chain can be anything, you only need to use canonical form when computing the hash).

@ozgrakkurt 
>This might be because we are using a hashmap structure to hold these

We aren't using either of these structures for the body, only for other types that are purely maps with a single key type. For those we use a mix of BTreeMap (ordered) and LinkedHashMap (arbitrary order, preserves insert order). It's a plain rust struct for TransactionBody.

I'm also in the middle of work to do a big change (see #393) which will use a bunch of improvements I've done in cddl-codgen to allow us to preserve the deserialized format (since CBOR allows arbitrary key ordering, + there are 2 ways to encode list lengths: definite (length encoded first) vs indefinite (special "break" code printed at the end)).

**Comment by ozgrakkurt** [comment]
@rooooooooob got it, thank you
