### ISSUE TITLE
TransactionOutputKind requested

### ISSUE THREAD

**Issue by Scitz0** [Emurgo/cardano-serialization-lib#498]
While implementing new ledgerjs 5.1.0 I noticed that it requires knowing the type of outputs, if its pre babbage or not, ie array vs map. 

Could we add a field like for TransactionMetadatumKind or PlutusDataKind, called for example TransactionOutputKind where the type is defined as Map or List?
This Kind could be a param of TransactionOutput.

Or is there some other way to identify if it's a map or array for outputs?

**Comment by lisicky** [comment]
Hi @Scitz0 ! Now CSL doesn't store any information in a TransactionOutput about that if pre-babbage is it or not. CSL serialize a TransactionOutput to the babbage format only if the TransactionOutput has inlined datum or inlined script. But I can't guarantee that logic won't change. If you deserialize a TransactionOutput there isn't way to check what format was it, except if you check cbor by yourself.

**Comment by lisicky** [comment]
@Scitz0 In general, if you use generated by 3-rd party tool tx, there isn’t a guarantee that CSL serializes tx in the same CBOR after deserialization. Because there are huge numbers of ways how the same data can be stored in a CBOR. Array or map can be serialized with definite or indefinite length, or one number can be serialized as 2 bytes or 4 bytes value. Also order in a map or array can be changed. And map or array in a babbage tx output is only just the tip of the iceberg. CSL doesn’t store info about original formants for all fields in a tx. The problem is slightly deeper than it seems. I can suggest you store the original cbor of the tx body when you deserialize it with read-only purpose, also if you have full tx cbor as input we probably can provide a function that extracts the original cbor of tx body from tx. But if you clarify your case step by step we probably suggest more options to solve your problem.

**Comment by Scitz0** [comment]
@lisicky I understand that a tx can be built & deserialized in different ways, and this is fine. We only use CSL, in this case, to read out the data in the tx to be able to pass data along as payload to Ledger HW device. The Ledger device needs to be able to reconstruct the tx internally exactly as it was originally created. This is why we need to specify if the output in source tx was generated as a map or array. 

Let me explain how Cardano CIP-30 dapp connector flow works, used by all sw wallets, and specifically for our wallet as we use CSL. I'm also assuming the user wallet is a Ledger HW device.

1. dApp creates an unsigned tx and sends this to the connected wallet.
2. We deserialize this tx cbor with CSL.
3. A JSON payload is generated according to [this data type](https://github.com/vacuumlabs/ledgerjs-cardano-shelley/blob/develop/src/types/public.ts#L1105).
4. Ledger device use this to generate an identical tx body as source tx to witness. 
5. We as a wallet return witnesses for source tx to dApp. Only the witnesses, not the passed in tx.
6. dapp assemble tx sent in 1 with returned witnesses and so on. 

I hope this makes flow clearer and why we need to know what type was used in cbor for original tx body.

**Comment by Scitz0** [comment]
For now I decided to decode cbor passed in manually to figure out the type, so not an immediate need now from my pov. But I still think, if CSL decodes a TX, that it should keep the original format and not convert it. I also still think type would be valid to add to the TransactionOutput object.

**Comment by vsubhuman** [comment]
> I still think, if CSL decodes a TX, that it should keep the original format and not convert it. I also still think type would be valid to add to the TransactionOutput object.

Good point, @Scitz0, we'll look into it and might be planned for the next version

**Comment by lisicky** [comment]
The function is ready. Check the new release: https://github.com/Emurgo/cardano-serialization-lib/releases/tag/11.4.0
