### ISSUE TITLE
Memory managment of serialization lib on javascript

### ISSUE THREAD

**Issue by AngelCastilloB** [Emurgo/cardano-serialization-lib#542]
Hi, I am currently trying to implement proper memory management and disposal of the CSL objects in the projects I have that use this library, but I would like to understand how far I need to go to properly dispose of all the objects, do I need to call free on every object that I create using one of the constructors, or is it enough to free the parent object?, for example, when creating a transaction we need to provide all sort of objects (redeemers, datums, signatures, input, outputs etc), is it enough to free the transaction where these objects have been added to it or we must free all of the objects individually? The same question goes for objects we get from other objects, do we need to manually free all these objects returned by the getters, or is it enough to free the parent object?.

**Comment by vsubhuman** [comment]
@AngelCastilloB , you do need to free every single object ever produced. Nearly always any data passed into a Rust call or received from Rust is cloned, to stop consuming of values from JS and preserve the usual JS code expectations. This means that there's no direct link between the value you have created in your JS code, e.g. a datum, and the value that it contained within a transaction struct, once you have passed that datum in - that information is cloned at the moment of passing it into a setter.

**Comment by vsubhuman** [comment]
@AngelCastilloB , if I remember things correctly the issue is not in this function specifically but in the bindgen processing of `JsError` from Rust in general. Any time any JS error is thrown from a Rust/WASM call - it leaks memory, as the Rust produced error object is never returned into JS and instead is converted into a JS native thrown error so it cannot be freed.

The only solution to this is to not rely on errors as business-logic, instead check values separately and then only call the function when you expect for the error to not happen.

We can add `is_valid_bech32(str) -> bool` function, if needed, which will not produce an error and will only return a boolean.

**Comment by rooooooooob** [comment]
@vsubhuman @AngelCastilloB  I believe this is what you're referring to rustwasm/wasm-bindgen#1963 which has been fixed already.

Just update the dependency, no need to add functionality.

**Comment by rooooooooob** [comment]
Note: at least when we updated it in CML, it had some changes in how errors were handled (since there are both `JsValue` and `JsError` types in `wasm_bindgen` but we also had our own `JsError` type and some blanket use wasm_bindgen::*; statements made things use that instead). I am not sure if CSL will run into that exact issue since we did quite a bit of refactoring, but just a heads up.

**Comment by vsubhuman** [comment]
> while (true) {
>  try {
>    
> // Throws and doesnt returns the object
> CSL.Address.from_bech32('37btjrVyb4KC6N6XtRHwEuLPQW2aa9JA89gbnm67PArSi8E7vGeqgA6W1pFBphc1hhrk1WKGPZpUbnvYRimVLRVnUH6M6d3dsVdxYoAC4m7oNj7Dzp')
>  } catch(error) {
>    console.log(error);
>  }
> }

@AngelCastilloB , this is actually my mistake to agree this is an issue that needs fixing. In your example the memory leak is not caused by the library at all. In the current latest library version just having a raised error does not cause a leak and if you change your example to something like this, it will not demonstrate a leak:

```
function parseBech32(str) {
    try {
      // Throws and doesnt returns the object
      return CSL.Address.from_bech32(str);
    } catch(e) {}
    return null;
}

while (true) {
  const a = parseBech32('37btjrVyb4KC6N6XtRHwEuLPQW2aa9JA89gbnm67PArSi8E7vGeqgA6W1pFBphc1hhrk1WKGPZpUbnvYRimVLRVnUH6M6d3dsVdxYoAC4m7oNj7Dzp');
  if (a != null) {
    console.log('address: ', a);
  }
}
```

There will be no memory leak visible. The problem in your code example is that logging an object in JS stops it from being garbage collected, so you just force all produced error instances to be stored forever. Even if you try logging anything, like an empty string, on every single `while (true)` iteration you will get a huge memory leak, because console logging is just that expensive. E.g.:

```
while (true) {
  const a = parseBech32('37btjrVyb4KC6N6XtRHwEuLPQW2aa9JA89gbnm67PArSi8E7vGeqgA6W1pFBphc1hhrk1WKGPZpUbnvYRimVLRVnUH6M6d3dsVdxYoAC4m7oNj7Dzp');
  if (a == null) {
    console.log('failed to parse');
  }
}
```

Causes a leak. But:

```
let i = 0;
while (true) {
  const a = parseBech32('37btjrVyb4KC6N6XtRHwEuLPQW2aa9JA89gbnm67PArSi8E7vGeqgA6W1pFBphc1hhrk1WKGPZpUbnvYRimVLRVnUH6M6d3dsVdxYoAC4m7oNj7Dzp');
  if (a == null) {
    if (i++ % 100000 === 0) {
      console.log('failed to parse 100K times');
    }
  }
}
```
Does not cause a leak (actually does, but just 100K times slower).

**Comment by vsubhuman** [comment]
> @vsubhuman I apologizes for the late reply, I did tested it and indeed it seems the problem is solved or at least improved, I could run my sample code for a long time without a crash

@AngelCastilloB, thank you for the feedback! 🙌

**Comment by vsubhuman** [comment]
A non-beta version `11.1.1` with this change is now published

**Comment by lisicky** [comment]
Thanks @klntsky ! It's a good package :) But have you tried to build CSL with WASM_BINDGEN_WEAKREF=1  env ? It might be better if you wanna to have automatic calling `free` function. This flag do similar things, see the [link](https://github.com/rustwasm/wasm-bindgen/blob/3c1f5a9e3ee197988ab9afe35d7244b751ad8cbb/crates/cli-support/src/js/mod.rs#L940)

**Comment by klntsky** [comment]
@lisicky thank you! We didn't know about it. Why isn't CSL compiled with it by default?
