### ISSUE TITLE
[ Question/Help ] Does this library work with Nami?

### ISSUE THREAD

**Issue by hariroshan** [Emurgo/cardano-serialization-lib#570]
I'm a beginner trying to learn about interacting with cardano wallets. I came across this repo [yoroi-frontend](https://github.com/Emurgo/yoroi-frontend/). Trying to implement `signTx` with `Nami` wallet using the same steps as shown in the repo, gives me this error

```js
{info: "Inputs do not conform to this spec or are otherwise invalid.", code: -1}
```

I'm trying to send `10 TADA` to `testnet faucet` using CIP 30 interface with Nami wallet instead of Yoroi. I have called `enable()` and have access to `API`

Can anyone help me ?

**Comment by Godspeed-exe** [comment]
Hello @hariroshan 

Thanks for reaching out.
I would suggest to redirect your question (**please also include an example your code**) to https://cardano.stackexchange.com/questions . Github issues are more focused on solving actual issues instead of coding help.

Below link also has an example of how to build a transaction and how to add these inputs, but this can be a bit outdated: https://github.com/Emurgo/cardano-serialization-lib/blob/master/example/index.spec.ts

I hope it helps!

**Comment by lisicky** [comment]
Hi @hariroshan ! It hard to localize your problem without additional information. Did you try to sign a tx only via nami or you tried other ways ?

**Comment by hariroshan** [comment]
Hello @lisicky & @Godspeed-exe, 

Thanks for the help. I found a project which does transaction in both Yoroi and Nami wallet. I'm leaving the link here for beginners like me.

https://github.com/dynamicstrategies/cardano-wallet-connector/blob/master/src/App.js

**Comment by lisicky** [comment]
@hariroshan Could you tell me this project helped you or you still have the issue with signing a tx ?

**Comment by hariroshan** [comment]
This project solved the issue I was having. And the comments made it clear for me

**Comment by lisicky** [comment]
@hariroshan Thanks for answer and link for a project!
