### ISSUE TITLE
multiple input addresses

### ISSUE THREAD

**Issue by dev-dantealighieri** [Emurgo/cardano-serialization-lib#673]
Hi,

I want to create an offline transaction, and sign it on an offline computer using npm library `elliptic`.

I can create transactions from one input address to multiple output addresses using your library, what i want is to have more than 1 different input addresses, and create `many-input/many-output` transactions such as in Bitcoin.

Is there way for creating a `data to sign`, and somehow sign it using the private keys of 2 different addresses?

If so, how can I do it?

thanks, Dante

**Comment by maintenance00** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
Thank you for posting @dev-dantealighieri

**Comment by lisicky** [comment]
Hey @dev-dantealighieri ! I hope you are well on all 9 circles of hell, because current one 10th ( yeah, times changing) 

To build in transaction in the CSL I recommend you `TransactionBuilder` type. It has `set_inputs` that accepts instance of `TxInputsBuilder` and by `TxInputsBuilder` you can specify any number of inputs, till it reaches transaction size limit
