### ISSUE TITLE
transaction hash differs from node/cli

### ISSUE THREAD

**Issue by error1100** [Emurgo/cardano-serialization-lib#696]
Hey there, unfortunately I'm seeing different tx hashes vs what the node code produces.

One example: 

- tx id on chain: a5f678bdf70101480f058a0845e94db04b6f1875155877a42a7c73a9bae5c5f4
- tx id calculated via cardano-cli: a5f678bdf70101480f058a0845e94db04b6f1875155877a42a7c73a9bae5c5f4
- tx id calculated by via transaction_hash: 3ea4b79bc55863e8c7a9f9e177ac64274372baab71194a373188bbbc0fc65a62

```
const csl = require("@emurgo/cardano-serialization-lib-nodejs");

const txHex = '84a300838258200...00ad7b401f5f6';
const tx = csl.Transaction.from_hex(txHex);
const txBody = tx.body();
const txHash = csl.hash_transaction(txBody);
const txId = txHash.to_hex();

console.log(`txId: ${txId}`);
```

cborHex attached.
[tx.signed.txt](https://github.com/user-attachments/files/17283378/tx.signed.txt)

Edit: tested with 12.1.1

**Comment by lisicky** [comment]
Hi @error1100! It because the `Transaction` type has no guarantee that CBOR will be the same after serialization roundtrip.
To avoid this issue you can use `FixedTransaction` type and get tx hash directly from this type. 
```js
const txHex = '84a300838258200...00ad7b401f5f6';
const tx = csl.FixedTransaction.from_hex(txHex);
const txHash = tx.transaction_hash()
```

`FixedTransaction` is aimed to avoid most of issues when you need to sign a tx from a third party.  You can sign or add signature by the next functions:

```js
.sign_and_add_vkey_signature()
.sign_and_add_icarus_bootstrap_signature()
.sign_and_add_daedalus_bootstrap_signature()
.add_vkey_witness()
.add_bootstrap_witness()
```

**Comment by error1100** [comment]
Thank you! Switching to FixedTransaction solves the issues.
