### ISSUE TITLE
Derivation scheme (possible) inconsistency for 12-word mnemonics

### ISSUE THREAD

**Issue by refi93** [Emurgo/cardano-serialization-lib#77]
I noticed for test case

https://github.com/Emurgo/cardano-serialization-lib/blob/0b2c0c1f0c5ed6a24862047b41070a1769dd9225/example/index.spec.ts#L61

That the expected result is obtained using the `V2` derivation scheme (probably as a result of having the scheme hardcoded here: https://github.com/Emurgo/cardano-serialization-lib/blob/f915b6a63a12f16addad9c163a13defc9031933c/rust/src/chain_crypto/derive.rs#L11), although AFAIK, 12-word mnemonics belong to legacy Daedalus wallets which were using `V1` scheme and AFAIK Daedalus does not support derivation of base addresses for them, prompting the users to migrate to shelley-ready wallets based on 15/24 word mnemonics.

Is this derivation scheme "inconsistency" just a matter of the tests or are there actually 12-word mnemonics which we should be using V2 derivation scheme for?

**Comment by SebastienGllmt** [comment]
> are there actually 12-word mnemonics which we should be using V2 derivation scheme for

I wouldn't be surprised if some wallets out there implemented Icarus keys (v2) on 12-word recovery phrases. Especially because multi-currency wallets usually have one root recovery phrase for all their coins and most likely they provide a 12-word option.

Using 15-words or higher for non-legacy wallets is just something we (IOHK + EMURGO) have have for simplicity, but nothing enforces this.
